#Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/hywro">twitter</a>'

style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
