#Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - record.md
  - contact.md

footer: 'Everything begins with your stance. Remember / Follow me on <a href="https://twitter.com/hywro">twitter</a>'

style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
